### ISSUE TITLE
Hi from tests-ex-markdown!

### ISSUE THREAD

**Issue by anko** [pjeby/mockdown#1]
I saw wooorm/mdast#39 and clicked through, since this looked interesting.

I've written a very similar tool called [tests-ex-markdown](https://github.com/anko/tests-ex-markdown), also using mdast, without knowing about your efforts. We seem to have written almost the same program only a couple of months apart! :smile:

The central difference seems to be that _txm_ is minimal and language-agnostic, while _mockdown_ is primarily for JS, with great features specialised for it.

I want to mention mockdown in txm's readme as an alternative. Do you think the above is a fair wording?

**Comment by pjeby** [comment]
Pretty much.  As of later this evening, though, mockdown will actually support any compile-to-JS language, with Babel and CoffeeScript support baked in, and others available by adding an appropriate chunk of glue code to the options.  (I've got it working in my checkout, writing up the revised docs right now.)

I did actually look at tests-ex-markdown before I started work on mockdown, but I _really_ wanted to have _narrative_ tests, where you can e.g. define a function in one code sample and then call it in another.  And I wanted them to be part of my mocha suites, run from gulp.  All of those things seemed to really be going against the grain of txm, so I decided to do my own.  (Also, I didn't see a way to do the equivalent of `wait()` in txm.)

So, ISTM the key difference is that mockdown is specialized for narrative testing of JS (and compile-to-JS) languages, using mocha as a testing and reporting engine instead of TAP.

(That being said, mockdown can more or less _emulate_ txm if you use mocha-tap-reporter and define a language engine whose "compiler" just pipes the example source to another program and then returns a JS constant for its output.  ;-)   But obviously, that's not its strong point.)

**Comment by sidorares** [comment]
same story - saw this in my feed, added you to "see also" of my similar project  - https://github.com/sidorares/mocha.md

**Comment by pjeby** [comment]
@sidorares Yep, your "see also" is how I found txm, actually.  Are you still working on mocha.md?

**Comment by anko** [comment]
[Both readme'd](https://github.com/anko/tests-ex-markdown/blob/4a4289e895640e187d2319c213ea8e079156055e/readme.markdown#similar-libraries)!

I hadn't thought about narrative testing at all. My use-cases were [eslisp](https://github.com/anko/eslisp) and [whatxml](https://github.com/anko/whatxml) docs, where I just needed to `require` and run a single pure function, repeatedly. For more complex interfaces, mockdown is way easier. Thanks for your work!

**Comment by pjeby** [comment]
No problem, I'm glad to have the feedback.  I hope you both will update me if you happen to use mockdown for anything -- especially anything that runs asynchronously, as that part of mockdown is still pretty immature as yet.  I have more features planned (per the [Roadmap](https://github.com/pjeby/mockdown/wiki/Roadmap), but even more vague misgivings about what might or might not be missing or suboptimal.  ;-)
